### ISSUE TITLE
Filtering folders

### ISSUE THREAD

**Issue by barcar** [gordonaspin/icloud_drive_sync#3]
Is it possible to limit the sub-folders being synced? I don’t need to sync my whole iCloud Drive.

**Comment by gordonaspin** [comment]
Yes, you can use the pseudoroot option:
```shell
icloudds -h
--pseudoroot <pseudoroot>       Folder within iCloud Drive sync (i.e.,
                                exclude all other folders)
``` 

If you have a subfolder (from the root) such as “My SubFolder”, you would use:

```shell
Icloudds -u <username> -d /some/local/folder –pseudoroot “My SubFolder”
```

**Comment by gordonaspin** [comment]
So in effect it’s either one or all subfolders. I guess I could make a couple of new options such as –exclude-folders and/or –include-folders.

**Comment by barcar** [comment]
Amazing, thanks, one folder is all I need.
